### ISSUE TITLE
Not and issue. Just thought about the name

### ISSUE THREAD

**Issue by YarikTH** [m1op1x/mio#3]
The name "mio" is already used for the popular library for mapping files to memory https://github.com/mandreyel/mio.

If you plan to promote your library to a wide auditory, then name clash definitely would be an issue. If it is a hobby project just for personal use, then this is not a problem.

**Comment by m1op1x** [comment]
Thank you for letting me know, I wasn't aware of this project. This is just a hobby project, but maybe it would be nice if I didn't have to think about this later. I will leave this open for a bit..

**Comment by m1op1x** [comment]
I don't believe this project will grow beyod hobby status, the naming should not be an issue.
